<?php
class NhanVien {
    public $__hoTen;
    public $__ngaySinh;
    public $__gioiTinh;
    public $__ngayVaoLam;
    public $__heSoLuong;
    public $__soCon;
    public $__thamNien;
    public const LUONGCANBAN = 450000;

    function XuLy() {
        if(isset($_POST['tinhluong'])) :
            $this->__hoTen = !empty($_POST['hovaten']) ? $_POST['hovaten'] : '';
            $this->__ngaySinh = !empty($_POST['ngaysinh']) ? $_POST['ngaysinh'] : '';
            $this->__gioiTinh = !empty($_POST['gioitinh']) ? $_POST['gioitinh'] : '';
            $this->__ngayVaoLam = !empty($_POST['ngayvaolam']) ? $_POST['ngayvaolam'] : '';
            $this->__heSoLuong = !empty($_POST['hesoluong']) ? floatval( $_POST['hesoluong'] ) : 0.0;
            $this->__soCon = !empty($_POST['socon']) ? intval( $_POST['socon'] ) : 0;
        endif;
    }
    function TroCap() {
        return $this->__soCon * 100000;
    }
    function TienLuong() {
        return self::LUONGCANBAN * $this->__heSoLuong;
    }
    function ThucLinh() {
        return $this->TienLuong() + $this->TroCap();
    }
}
class NhanVienVanPhong extends NhanVien {
    public $__soNgayVang;
    public const DINHMUCVANG = 2;
    public const DINHMUCPHAT= 25000;
    public function XuLy()
    {
        parent::XuLy();
        $this->__soNgayVang = !empty($_POST['songayvang']) ? intval($_POST['songayvang']) : 0;
    }

    function TienPhat() {
        if($this->__soNgayVang > self::DINHMUCVANG)
            return ( $this->__soNgayVang - self::DINHMUCVANG ) * self::DINHMUCPHAT;
        return 0;
    }
    function TroCap() {
        if($this->__gioiTinh === 'Nu')
            return $this->__soCon * 100000 * 1.2;
        return parent::TroCap();
    }
    function TienLuong() {
        return parent::TienLuong() - $this->TienPhat();
    }

}
class NhanVienSanXuat extends NhanVien {
    public $__soSanPham;
    public $__dinhMucSanPham = 100;
    public $__donGiaSanPham = 12000;
    public function XuLy()
    {
        parent::XuLy(); // TODO: Change the autogenerated stub
        $this->__soSanPham = !empty($_POST['sosanpham']) ? $_POST['sosanpham'] : 0;
    }

    function TienThuong() {
        if($this->__soSanPham > $this->__dinhMucSanPham)
            return ( $this->__soSanPham - $this->__dinhMucSanPham ) * $this->__donGiaSanPham * 0.05;
        else
            return ( $this->__soSanPham - $this->__dinhMucSanPham ) * $this->__donGiaSanPham * 0.01;
    }
    function TroCap() {
        global $role;
        $tangca = isset($_POST['tangca']) ? $_POST['tangca'] : '';
        if($tangca === 'co' && $role === 'sx')
            return parent::TroCap() + 200000;
        return parent::TroCap();
    }
    function TienLuong() {
        return $this->__soSanPham * $this->__donGiaSanPham + $this->TienThuong();
    }
}


/**
 * Kiểm tra loại nv và trả về loại nv tương ứng
 */
function getUserRole() {
    return isset($_POST['loainhanvien']) ? $_POST['loainhanvien'] : '';
}
$role = getUserRole();
// Dựa vào giá trị của $role, tạo một thể hiện của class tương ứng
if ($role === 'vp') {
    $user = new NhanVienVanPhong();
    $user->XuLy();


} else {
    $user = new NhanVienSanXuat();
    $user->XuLy();
}

?>
<?php //= isset($_POST['tinhluong']) ? number_format($user->TienPhat()) : ''; ?>
<!doctype html>
<html lang="en" ng-app="myApp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
</head>
<body ng-controller="myCtrl">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-9">
            <div class="card">
                <div class="card-header text-center text-uppercase bg-warning-subtle">Quản lý nhân viên</div>
                <div class="card-body">
                    <form action="" method="post" class="row g-3 justify-content-center">
                        <div class="col-2 align-content-around">
                            <label class="form-label">Họ và tên</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="hovaten" value="<?= !empty($user->__hoTen) ? $user->__hoTen : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Số con</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="socon" value="<?= !empty($user->__soCon) ? $user->__soCon : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Ngày sinh</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="ngaysinh" value="<?= !empty($user->__ngaySinh) ? $user->__ngaySinh : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Ngay vào làm</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="ngayvaolam" value="<?= !empty($user->__ngayVaoLam) ? $user->__ngayVaoLam : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Giới tính</label>
                        </div>
                        <div class="col-4">
                            <input type="radio" name="gioitinh" id="" value="Nam" <?= $user->__gioiTinh === 'Nam' ? 'checked' : ''; ?>> Nam
                            <input type="radio" name="gioitinh" id="" value="Nu" <?= $user->__gioiTinh === 'Nu' ? 'checked' : ''; ?>> Nữ
                        </div>
                        <div class="col-2">
                            <label class="form-label">Hệ số lương</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="hesoluong" value="<?= !empty($user->__heSoLuong) ? $user->__heSoLuong : ''; ?>">
                        </div>
                        <div class="col-4">
                            <label class="form-label">Loại nhân viên</label>
                        </div>
                        <div class="col-4">
                            <input type="radio" name="loainhanvien" value="vp" id="nhanvienvp" <?= $role === 'vp' ? 'checked' : ''; ?>> Văn phòng
                        </div>
                        <div class="col-4">
                            <input type="radio" name="loainhanvien" value="sx" id="nhanviensx" <?= $role === 'sx' ? 'checked' : ''; ?>> Sản xuất
                        </div>
                        <div class="col-2">
                            <label class="form-label">Số ngày vắng</label>
                        </div>
                        <div class="col-2">
                            <input type="text" class="form-control" name="songayvang" value="<?= !empty($user->__soNgayVang) ? $user->__soNgayVang : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Số sản phẩm</label>
                        </div>
                        <div class="col-2">
                            <input type="text" class="form-control" name="sosanpham" value="<?= !empty($user->__soSanPham) ? $user->__soSanPham : ''; ?>">
                        </div>
                        <div class="col-2">
                            <label class="form-label">Tăng ca</label>
                        </div>
                        <div class="col-2">
                            <input type="radio" name="tangca" id="" value="co" <?= (isset($_POST['tangca']) && $_POST['tangca'] === 'co') ? 'checked' : '' ?>
                            > Có
                            <input type="radio" name="tangca" id="" value="khong" <?= (isset($_POST['tangca']) && $_POST['tangca'] === 'khong') ? 'checked' : '' ?>
                            > Không
                        </div>
                        <div class="col-2">
                            <label class="form-label">Tiền lương</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="tienluong" value="<?= isset($_POST['tinhluong']) ? number_format($user->TienLuong()) : ''; ?>" readonly>

                        </div>
                        <div class="col-2">
                            <label class="form-label">Trợ cấp</label>
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" name="trocap" value="<?= isset($_POST['tinhluong']) ? number_format($user->TroCap()) : ''; ?>" readonly>
                        </div>
                        <div class="col-3 text-end">
                            <label class="form-label">Thực lĩnh</label>
                        </div>
                        <div class="col-6">
                            <input type="text" class="form-control" name="thuclinh" value="<?= isset($_POST['tinhluong']) ? number_format($user->ThucLinh()) : ''; ?>" readonly>
                        </div>
                        <div class="col-12 text-center">
                            <button name="tinhluong" class="btn btn-primary">Tính lương</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="../assets/js/angular.min.js"></script>
<script>
    const app = angular.module('myApp', []);
    app.controller('myCtrl', $scope => {

    });
</script>
</body>
</html>